// <auto-generated />
namespace DataMgmt.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_course_batch_relation_add_batch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_course_batch_relation_add_batch));
        
        string IMigrationMetadata.Id
        {
            get { return "201712181248033_change_course_batch_relation_add_batch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
