// <auto-generated />
namespace DataMgmt.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class explicit_relation_subject_semester : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(explicit_relation_subject_semester));
        
        string IMigrationMetadata.Id
        {
            get { return "201801021340583_explicit_relation_subject_semester"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
